export type AuditRequestFormData = {
  name: string;
  email: string;
  url: string;
  industry: string;
  goal: string;
  challenge: string;
  focusAreas: string[];
};

export type Archetype = "Hero" | "Sage" | "Outlaw" | "Caregiver" | "Creator" | "Ruler";

export type JourneyStage = "arrival" | "understanding" | "trust-building" | "decision" | "action";

// The AI's diagnosis is the product — no rule checks, no scores. Each break is
// anchored to one journey stage and carries its own concrete fix + ready-to-use
// AI prompt, generated by the same call that wrote the narrative verdict.
export type JourneyBreak = {
  journeyStage: JourneyStage;
  element: string;
  whatsHappening: string;
  whatShouldHappen: string;
  reason: string;
  fix: string;
  aiPrompt: string;
};

export type DomData = {
  navLinks: string[];
  h1Text: string;
  h2Texts: string[];
  ctaTexts: string[];
  paragraphTexts: string[];
  testimonialTexts: string[];
  trustLogoLabels: string[];
  pricingTiers: { name: string; price: string }[];
  imagesCount: number;
  hasForm: boolean;
  metaTitle: string;
};

export type AuditData = {
  auditId: string;
  url: string;
  domain: string;
  createdAt: string;
  domData: DomData;
  currentArchetype: Archetype | null;
  targetArchetype: Archetype | null;
  narrativeVerdict: string | null;
  revenueLeakEstimate: string | null;
  journeyBreaks: JourneyBreak[] | null;
  diagnosisError: string | null;
  rawHtml?: string | null;
};
